<a href="https://colab.research.google.com/github/alful/Data_Mining/blob/main/Preprocessing/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [265]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [266]:
dataset = pd.read_csv('diabetes.csv')
x= dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

print(x)

[[  6. 148.  72.  35.  nan   5.]
 [  1.  85.  66.  29.  nan  31.]
 [  8. 183.  64.  nan  nan  32.]
 [  1.  89.  66.  23.  94.  21.]
 [  0. 137.   4.  35. 168.  33.]
 [  5. 116.  74.  nan  nan   3.]
 [  3.  78.   5.  32.  88.  26.]
 [ 10. 115.  nan  nan  nan  29.]
 [  2. 197.   7.  45. 543.  53.]
 [  8. 125.  96.  nan  nan  54.]
 [  4.  11.  92.  nan  nan   3.]
 [ 10. 168.  74.  nan  nan  34.]
 [ 10. 139.   8.  nan  nan  57.]
 [  1. 189.   6.  23. 846.  59.]
 [  5. 166.  72.  19. 175.  51.]
 [  7.   1.  nan  nan  nan  32.]
 [  0. 118.  84.  47.  23.  31.]
 [  7.  17.  74.  nan  nan  31.]
 [  1.  13.   3.  38.  83.  33.]
 [  1. 115.   7.   3.  96.  32.]
 [  3. 126.  88.  41. 235.  27.]
 [  8.  99.  84.  nan  nan   5.]
 [  7. 196.   9.  nan  nan  41.]
 [  9. 119.   8.  35.  nan  29.]
 [ 11. 143.  94.  33. 146.  51.]
 [ 10. 125.   7.  26. 115.  41.]
 [  7. 147.  76.  nan  nan  43.]
 [  1.  97.  66.  15.  14.  22.]
 [ 13. 145.  82.  19.  11.  57.]
 [  5. 117.  92.  nan  nan  38.]
 [  5.  19

In [267]:
print(y)

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0]


In [268]:
from sklearn.impute import SimpleImputer;
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:5])
x[:,1:5]=imputer.transform(x[:,1:5])

In [269]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
cy=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x));

In [270]:
print(x);

[[  0.        0.        0.        0.        0.        0.        1.
    0.        0.        0.        0.        0.        0.      148.
   72.       35.      183.5       5.     ]
 [  0.        1.        0.        0.        0.        0.        0.
    0.        0.        0.        0.        0.        0.       85.
   66.       29.      183.5      31.     ]
 [  0.        0.        0.        0.        0.        0.        0.
    0.        1.        0.        0.        0.        0.      183.
   64.       28.55    183.5      32.     ]
 [  0.        1.        0.        0.        0.        0.        0.
    0.        0.        0.        0.        0.        0.       89.
   66.       23.       94.       21.     ]
 [  1.        0.        0.        0.        0.        0.        0.
    0.        0.        0.        0.        0.        0.      137.
    4.       35.      168.       33.     ]
 [  0.        0.        0.        0.        0.        1.        0.
    0.        0.        0.        0.        0.  

In [271]:
from sklearn.preprocessing import LabelEncoder;
le=LabelEncoder();
y=le.fit_transform(y);

In [272]:
print(y);

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0]


In [273]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
print(x_train)

[[  0.        0.        0.        0.        0.        0.        0.
    1.        0.        0.        0.        0.        0.      196.
    9.       28.55    183.5      41.     ]
 [  1.        0.        0.        0.        0.        0.        0.
    0.        0.        0.        0.        0.        0.      137.
    4.       35.      168.       33.     ]
 [  0.        0.        0.        0.        0.        0.        0.
    0.        1.        0.        0.        0.        0.      183.
   64.       28.55    183.5      32.     ]
 [  0.        0.        0.        0.        0.        0.        0.
    0.        1.        0.        0.        0.        0.       99.
   84.       28.55    183.5       5.     ]
 [  0.        0.        0.        0.        0.        0.        0.
    0.        0.        1.        0.        0.        0.      119.
    8.       35.      183.5      29.     ]
 [  0.        0.        0.        0.        1.        0.        0.
    0.        0.        0.        0.        0.  

In [274]:
print(x_test)

[[  0.     0.     0.     0.     0.     1.     0.     0.     0.     0.
    0.     0.     0.   166.    72.    19.   175.    51.  ]
 [  0.     1.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.   115.     7.     3.    96.    32.  ]
 [  0.     1.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.    89.    66.    23.    94.    21.  ]
 [  0.     1.     0.     0.     0.     0.     0.     0.     0.     0.
    0.     0.     0.    97.    66.    15.    14.    22.  ]
 [  0.     0.     0.     1.     0.     0.     0.     0.     0.     0.
    0.     0.     0.    88.    58.    11.    54.    22.  ]
 [  0.     0.     0.     0.     0.     0.     0.     1.     0.     0.
    0.     0.     0.   147.    76.    28.55 183.5   43.  ]
 [  0.     0.     0.     1.     0.     0.     0.     0.     0.     0.
    0.     0.     0.   126.    88.    41.   235.    27.  ]
 [  0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
    1.     0.     0.   125.

In [275]:
print(y_train)  

[1 1 1 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 1 1 1 1 0]


In [276]:
print(y_test)

[1 1 0 0 0 1 0 1 1 0 1]


In [277]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,13:] = sc.fit_transform(x_train[:,13:])
x_test[:,13:] = sc.transform(x_test[:,13:])

In [278]:
print(x_train)

[[ 0.          0.          0.          0.          0.          0.
   0.          1.          0.          0.          0.          0.
   0.          1.40630026 -1.23231548 -0.42664198 -0.14111922  0.53261272]
 [ 1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.32139437 -1.3737048   0.62911011 -0.23445689  0.04746054]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          1.          0.          0.          0.
   0.          1.1672532   0.32296701 -0.42664198 -0.14111922 -0.01318348]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          1.          0.          0.          0.
   0.         -0.37735857  0.88852428 -0.42664198 -0.14111922 -1.65057209]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          1.          0.          0.
   0.         -0.00959386 -1.26059334  0

In [279]:
print(x_test)

[[ 0.          0.          0.          0.          0.          1.
   0.          0.          0.          0.          0.          0.
   0.          0.8546532   0.54918992 -1.98980981 -0.19230439  1.13905294]
 [ 0.          1.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.         -0.0831468  -1.28887121 -4.60872973 -0.6680254  -0.01318348]
 [ 0.          1.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.         -0.56124092  0.37952274 -1.33507983 -0.68006897 -0.68026773]
 [ 0.          1.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.         -0.41413504  0.37952274 -2.64453979 -1.16181177 -0.61962371]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.         -0.57962916  0.15329983 -3