<a href="https://colab.research.google.com/github/alful/Data_Mining/blob/main/DecisionTree/decisiontree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [380]:
import numpy as np
import pandas as pd
from sklearn import tree

In [381]:
Diabetes = pd.read_csv('diabetes_zero.csv', delimiter=',', header=0)

In [382]:
Diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  Age  Outcome
0            6      148             72             35        0   50        1
1            1       85             66             29        0   31        0
2            8      183             64              0        0   32        1
3            1       89             66             23       94   21        0
4            0      137             40             35      168   33        1

In [383]:
print(Diabetes)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  Age  Outcome
0              6      148             72             35        0   50        1
1              1       85             66             29        0   31        0
2              8      183             64              0        0   32        1
3              1       89             66             23       94   21        0
4              0      137             40             35      168   33        1
..           ...      ...            ...            ...      ...  ...      ...
763           10      101             76             48      180   63        0
764            2      122             70             27        0   27        0
765            5      121             72             23      112   30        0
766            1      126             60              0        0   47        1
767            1       93             70             31        0   23        0

[768 rows x 7 columns]


In [384]:
Diabetes= Diabetes.drop(labels="Pregnancies",axis=1)

In [385]:
print(Diabetes)

     Glucose  BloodPressure  SkinThickness  Insulin  Age  Outcome
0        148             72             35        0   50        1
1         85             66             29        0   31        0
2        183             64              0        0   32        1
3         89             66             23       94   21        0
4        137             40             35      168   33        1
..       ...            ...            ...      ...  ...      ...
763      101             76             48      180   63        0
764      122             70             27        0   27        0
765      121             72             23      112   30        0
766      126             60              0        0   47        1
767       93             70             31        0   23        0

[768 rows x 6 columns]


In [386]:
Diabetes = Diabetes.to_numpy()

In [387]:
print(Diabetes)

[[148  72  35   0  50   1]
 [ 85  66  29   0  31   0]
 [183  64   0   0  32   1]
 ...
 [121  72  23 112  30   0]
 [126  60   0   0  47   1]
 [ 93  70  31   0  23   0]]


In [388]:
dataTraining = np.concatenate((Diabetes[0:330, :], Diabetes[380:710, :]), axis=0)
dataTesting = np.concatenate((Diabetes[330:380, :], Diabetes[710:760, :]), axis=0)

In [389]:
print(dataTraining)
len(dataTraining)

[[148  72  35   0  50   1]
 [ 85  66  29   0  31   0]
 [183  64   0   0  32   1]
 ...
 [127  46  21 335  22   0]
 [164  78   0   0  45   1]
 [ 93  64  32 160  23   1]]


660

In [390]:
print(dataTesting)
len(dataTesting)

[[118  72  19   0  46   0]
 [ 87  58  16  52  25   0]
 [180   0   0   0  41   1]
 [106  80   0   0  44   0]
 [ 95  60  18  58  22   0]
 [165  76  43 255  26   0]
 [117   0   0   0  44   0]
 [115  76   0   0  44   1]
 [152  78  34 171  33   1]
 [178  84   0   0  41   1]
 [130  70  13 105  22   0]
 [ 95  74  21  73  36   0]
 [  0  68  35   0  22   0]
 [122  86   0   0  33   0]
 [ 95  72   0   0  57   0]
 [126  88  36 108  49   0]
 [139  46  19  83  22   0]
 [116   0   0   0  23   0]
 [ 99  62  19  74  26   0]
 [  0  80  32   0  37   1]
 [ 92  80   0   0  29   0]
 [137  84   0   0  30   0]
 [ 61  82  28   0  46   0]
 [ 90  62  12  43  24   0]
 [ 90  78   0   0  21   0]
 [165  88   0   0  49   1]
 [125  50  40 167  28   1]
 [129   0  30   0  44   1]
 [ 88  74  40  54  48   0]
 [196  76  36 249  29   1]
 [189  64  33 325  29   1]
 [158  70   0   0  63   0]
 [103 108  37   0  65   0]
 [146  78   0   0  67   1]
 [147  74  25 293  30   0]
 [ 99  54  28  83  30   0]
 [124  72   0   0  29   1]
 

100

In [391]:
inputTraining = dataTraining[:, 0:5]
inputTesting = dataTesting[:, 0:5]
labelTraining = dataTraining[:, 5]
labelTesting = dataTesting[:, 5]

In [392]:
model = tree.DecisionTreeClassifier()

In [393]:
model = model.fit(inputTraining, labelTraining)

In [394]:
hasilPrediksi = model.predict(inputTesting)
print("label sebenarnya", labelTesting)
print("hasil prediksi", hasilPrediksi)

label sebenarnya [0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1
 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0
 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 0 1 0 1]
hasil prediksi [0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 1 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0
 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1]


In [395]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar: ", prediksiBenar, "data")
print("prediksi salah: ", prediksiSalah, "data")
print("akurasi: ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")


prediksi benar:  76 data
prediksi salah:  24 data
akurasi:  76.0 %
